source("R/process_dataset.R")

data_dir <- fs::path("D:/data/raw/datasus")
dest_dir <- fs::path("D:/data/intermediary/datasus")

process_dataset(fs::path(data_dir, "cnes-st"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-lt"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-dc"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-ee"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-ef"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-ep"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-eq"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-gm"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-hb"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-in"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-pf"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-rc"), dest_dir)
process_dataset(fs::path(data_dir, "cnes-sr"), dest_dir)
process_dataset(fs::path(data_dir, "sih-rd"), dest_dir)
process_dataset(fs::path(data_dir, "sih-sp"), dest_dir)
process_dataset(fs::path(data_dir, "sia-am"), dest_dir)
process_dataset(fs::path(data_dir, "siscolo-cc"), dest_dir)
process_dataset(fs::path(data_dir, "siscolo-hc"), dest_dir)
process_dataset(fs::path(data_dir, "sismama-cm"), dest_dir)
process_dataset(fs::path(data_dir, "sismama-hm"), dest_dir)
process_dataset(fs::path(data_dir, "sisprenatal-pn"), dest_dir)
process_dataset(fs::path(data_dir, "sia-sad"), dest_dir)
process_dataset(fs::path(data_dir, "sia-an"), dest_dir)
process_dataset(fs::path(data_dir, "cih-cr"), dest_dir)
process_dataset(fs::path(data_dir, "sia-pa"), dest_dir)
